# Manage generation/validation of URLs generated by present app and linking to itself
from config_rdr import config


def get_download_url(file_id: str) -> str:
    """
    Generate a download URL for a file.

    Args:
        file_id (str): The ID of the file to download

    Returns:
        str: The full URL to download the file
    """
    return f"{config.public_url}/download/{file_id}"


def is_download_url(url: str) -> bool:
    """
    Check if a URL is a download URL.

    Args:
        url (str): The URL to check

    Returns:
        bool: True if the URL is a download URL, False otherwise
    """
    return url.startswith(f"{config.public_url}/download/")


def extract_file_id_from_download_url(url: str) -> str:
    """
    Extract the file ID from a download URL.

    Args:
        url (str): The download URL

    Returns:
        str: The file ID extracted from the URL
    """
    if not is_download_url(url):
        raise ValueError(f"Not a download URL: {url}")

    return url.replace(f"{config.public_url}/download/", "")


def generate_scan_url(project_hash: str, sample_hash: str, subsample_hash: str) -> str:
    """
    Generate a URL for a scan.

    Args:
        project_hash (str): The project hash
        sample_hash (str): The sample hash
        subsample_hash (str): The subsample hash

    Returns:
        str: The full URL to the scan
    """
    return f"{config.public_url}/projects/{project_hash}/samples/{sample_hash}/subsamples/{subsample_hash}/scan.jpg"


def generate_background_url(project_hash: str, background_date: str) -> str:
    """
    Generate a URL for a background image.

    Args:
        project_hash (str): The project hash
        background_date (str): The background date

    Returns:
        str: The full URL to the background image
    """
    return (
        f"{config.public_url}/projects/{project_hash}/background/{background_date}.jpg"
    )
